# Generated by Django 5.2.7 on 2026-05-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='categorias/')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text='Ex: 15, 17, 19 (para colares/pulseiras) ou P, M, G', max_length=20, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('anel', 'Anel (número)'), ('colar', 'Colar (cm)'), ('pulseira', 'Pulseira (cm)'), ('brinco', 'Brinco (tamanho)'), ('geral', 'Geral (P/M/G)')], default='geral', max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
                'ordering': ['tipo', 'valor'],
                'unique_together': {('valor', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('disponivel', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.categoria')),
                ('tamanhos', models.ManyToManyField(blank=True, help_text='Selecione os tamanhos disponíveis para este produto', related_name='produtos', to='produtos.tamanho', verbose_name='Tamanhos disponíveis')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
