# Generated by Django 5.2.7 on 2026-05-13 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.categoria'),
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text='Ex: 15, 17, 19 (para colares/pulseiras) ou P, M, G', max_length=20, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('anel', 'Anel (número)'), ('colar', 'Colar (cm)'), ('pulseira', 'Pulseira (cm)'), ('brinco', 'Brinco (tamanho)'), ('geral', 'Geral (P/M/G)')], default='geral', max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
                'ordering': ['tipo', 'valor'],
                'unique_together': {('valor', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanhos',
            field=models.ManyToManyField(blank=True, help_text='Selecione os tamanhos disponíveis para este produto', related_name='produtos', to='produtos.tamanho', verbose_name='Tamanhos disponíveis'),
        ),
    ]
