# Generated by Django 5.2.7 on 2026-01-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_products_cartitem'),
        ('produtos', '0002_categoria_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='produtos.produto'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
